[package]
name = "kimyo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
color-eyre = "0.6"
httparse = "1.10.1"
mlua = { version = "0.9", features = ["lua54", "module"] }
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = "0.3"
urlencoding = "2.1"
